// <auto-generated />
namespace NuelClinics.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _Appointment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_Appointment));
        
        string IMigrationMetadata.Id
        {
            get { return "202204291019171__Appointment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
